shallow_clone:
  true

environment:
  GH_TOKEN:
    secure: 3nYUgwZOepfou2Ni6nyJAuvCw1/4u/TwM6JK6XSsquFOHSmqMUCz8uWRmxVMH5Sp
  matrix:
    - nodejs_version: "8"

branches:
  only:
  - master

platform:
  - x64

cache:
  - node_modules

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - ps: npm install --global --production windows-build-tools

before_build:
  - node --version && yarn --version && python --version

build_script:
  - yarn package -- --publish onTagOrDraft